  
name: check
on:
#  schedule:
#    - cron:  '0 6 * * *'
  push: {}
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
    
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      
      - run: chrome --remote-debugging-port=9223 --no-first-run --no-default-browser-check --headless --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36" &

      - name: check
        run: node index.js
        env:
          URL: ${{ secrets.URL }}
          NOTIFY_VIA: ${{ secrets.NOTIFY_VIA }}
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
          CSS_SELECTOR: ${{ secrets.CSS_SELECTOR }}
          UNWANTED_TEXT: ${{ secrets.UNWANTED_TEXT }}
